const $=(s,root=document)=>root.querySelector(s);
const $$=(s,root=document)=>[...root.querySelectorAll(s)];

const nav=$('nav');
if(nav) nav.innerHTML='<a href="edit.html">The edit</a><a href="study.html">Character study</a><a href="inner-world.html">Inner world</a><a href="panels.html">Manga panels</a>';
let motion=!matchMedia('(prefers-reduced-motion: reduce)').matches;
const motionButton=$('#motion');
function setMotion(){document.documentElement.classList.toggle('no-motion',!motion);if(motionButton){motionButton.setAttribute('aria-pressed',String(motion));motionButton.innerHTML=`Motion ${motion?'on':'off'} <span>${motion?'◉':'○'}</span>`;}}
setMotion();motionButton?.addEventListener('click',()=>{motion=!motion;setMotion();});
$('#play')?.addEventListener('click',()=>{window.location.href='edit.html';});

const prose=[
`I was going to do something extraordinary today.\nI hadn’t decided what, exactly. That was the small, unimportant part.\n\nThen the light caught the grass, and for a moment everything looked like it was made of me. Or maybe I was made of it.\n\nDon’t tell anyone I spent the morning looking. I’m calling it research.`,
`I said I’d find you something better. You looked at me as if a promise were just another thing I’d drop.\n\nFair enough. I drop a lot of things.\n\nBut I keep thinking about you out there after everyone else has gone inside. There must be something in this enormous world that needs the two of us.\n\nLet me keep looking.`,
`Everyone notices when I can do something I couldn’t do before. They look relieved. I try to look relieved, too.\n\nIt’s harder to explain the other part. The little pause where a familiar thought should be. A space so small I almost convince myself it was always there.\n\nTomorrow I’ll try again. Tonight, I’d like to remember what I was trying for.`];
const tabButtons=$$('[role=tab]');
const pieceMeta=[['ROOM 01 / OPEN SKY','WONDER'],['ROOM 02 / BETWEEN WORDS','DEVOTION'],['ROOM 03 / AFTERIMAGE','UNCERTAINTY']];
function selectPiece(i,focus=false){tabButtons.forEach((tab,n)=>{tab.setAttribute('aria-selected',String(n===i));tab.tabIndex=n===i?0:-1;});const text=$('#prose');if(text)text.textContent=prose[i];const panel=$('#writing-panel');if(panel)panel.setAttribute('aria-labelledby',tabButtons[i]?.id||'tab-0');if($('#piece-room'))$('#piece-room').textContent=pieceMeta[i][0];if($('#piece-mood'))$('#piece-mood').textContent=pieceMeta[i][1];if(focus)tabButtons[i]?.focus();}
tabButtons.forEach((tab,i)=>{tab.addEventListener('click',()=>selectPiece(i));tab.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight')n=(i+1)%3;if(e.key==='ArrowLeft')n=(i+2)%3;if(e.key==='Home')n=0;if(e.key==='End')n=2;if(n!==undefined){e.preventDefault();selectPiece(n,true);}});});
if($('#prose'))selectPiece(0);

const lensNames={philosophy:'East-philosophical',psychology:'Psychological erosion',parallels:'Parallels',world:'Integration to the world'};
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
let views=JSON.parse(localStorage.getItem('phos-views')||'null')||[{author:'Mira',lens:'philosophy',title:'A self made of relations',body:'Phos feels closest to anatta when they stop treating identity as a hidden core. Every encounter changes the shape of the person who returns.'},{author:'Jun',lens:'parallels',title:'The archive as a raft',body:'The encyclopedia begins as a task that keeps Phos away from the front line. It becomes a way to cross the distance between curiosity and care.'}];
function renderViews(){const list=$('#view-list');if(!list)return;list.innerHTML=views.map(v=>`<article class="view-card" data-lens="${escapeHtml(v.lens)}" data-keywords="${escapeHtml(`${v.title} ${v.body}`.toLowerCase())}"><small>${lensNames[v.lens]||v.lens}</small><h4>${escapeHtml(v.title)}</h4><p>${escapeHtml(v.body)}</p><footer>by ${escapeHtml(v.author)}<time>${v.date||'archived'}</time></footer></article>`).join('');}
renderViews();
$('#analysis-form')?.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));views=[{...data,date:'just now'},...views];localStorage.setItem('phos-views',JSON.stringify(views));e.currentTarget.reset();renderViews();document.querySelector('.view-card')?.scrollIntoView({behavior:'smooth',block:'center'});});
const search=$('#study-search'),count=$('#result-count'),empty=$('#study-empty');let activeLens='all';
function filterLibrary(){const q=(search?.value||'').trim().toLowerCase();let shown=0;$$('.library-card').forEach(card=>{const matchesLens=activeLens==='all'||card.dataset.lens===activeLens;const matchesQuery=!q||`${card.textContent} ${card.dataset.keywords}`.toLowerCase().includes(q);const visible=matchesLens&&matchesQuery;card.classList.toggle('is-hidden',!visible);if(visible)shown++;});if(count)count.textContent=`${shown} ${shown===1?'entry':'entries'}`;if(empty)empty.hidden=shown!==0;}
search?.addEventListener('input',filterLibrary);$$('.lens-chip').forEach(chip=>chip.addEventListener('click',()=>{$$('.lens-chip').forEach(c=>c.classList.toggle('active',c===chip));activeLens=chip.dataset.lens;filterLibrary();}));if(search)filterLibrary();
const dialog=$('#study-dialog');$$('.read-card').forEach(button=>button.addEventListener('click',()=>{if(!dialog)return;$('#dialog-lens').textContent=button.dataset.lens;$('#dialog-title').textContent=button.dataset.title;$('#dialog-body').textContent=button.dataset.body;dialog.showModal();}));$('.dialog-close')?.addEventListener('click',()=>dialog?.close());dialog?.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});

const scenes=[['assets/phos-field.png','01 / THE BEGINNING','Born to wonder.','A world is a thing you can keep looking at.'],['assets/phos-sun.png','02 / A LITTLE LIGHT','Let me be useful.','Even joy leaves an afterimage.'],['assets/phos-anime.jpg','03 / FIRST CONTACT','The question opens.','Curiosity is a door with no handle.'],['assets/phos-portrait.png','04 / ICON','A face becomes a symbol.','The self is watched into a shape.'],['assets/phos-sitting.png','05 / BODY','Stillness has a posture.','What changes first: the body or the story?'],['assets/phos-crescent.png','06 / MOON','Desire bends toward absence.','The faraway thing keeps calling.'],['assets/phos-water.png','07 / WATER','Identity keeps moving.','Memory refuses a clean edge.'],['assets/phos-black.png','08 / VOID','What remains after language.','Silence is also a material.'],['assets/phos-hands.png','09 / RITUAL','The self held by others.','No fragment becomes alone.']].map(([src,kicker,title,subtitle])=>({src,kicker,title,subtitle}));
let editIndex=0;const editStage=$('#edit-stage'),editImage=$('#edit-image');let editVideo;
if(editStage){const introTitle=$('.edit-intro h1');if(introTitle){introTitle.innerHTML='Phosphophyllite / motion edit';introTitle.classList.add('edit-title-compact');}const introEyebrow=$('.edit-intro .eyebrow');if(introEyebrow)introEyebrow.textContent='MOTION STUDY';const introCopy=$('.edit-intro>p');if(introCopy)introCopy.textContent='A short video portrait with light, impact, and afterimages.';$('.edit-corner')?.remove();editStage.querySelector('.edit-scanlines')?.insertAdjacentHTML('afterend','<video id="edit-video" playsinline preload="metadata" controls aria-label="Phosphophyllite motion edit"><source src="assets/phos-edit.webm" type="video/webm"><source src="assets/phos-edit.mp4" type="video/mp4"><track kind="captions" srclang="en" label="English CC" default src="assets/phos-edit.vtt"></video>');editVideo=$('#edit-video');editImage?.remove();
  const timeline=$('#timeline');scenes.forEach((s,i)=>{const b=document.createElement('button');b.className='timeline-step';b.innerHTML=`<small>${s.kicker.split(' / ')[1]}</small>`;b.addEventListener('click',()=>{if(editVideo){editVideo.currentTime=i*2.25;editVideo.pause();}renderScene(i);});timeline?.append(b);});
  editVideo?.addEventListener('timeupdate',()=>{const next=Math.min(scenes.length-1,Math.floor(editVideo.currentTime/2.25));if(next!==editIndex)renderScene(next,false);});editVideo?.addEventListener('ended',()=>{if($('#edit-pause'))$('#edit-pause').textContent='Replay';});
  renderScene(0,false);$('#edit-play')?.addEventListener('click',()=>{editVideo?.play();if($('#edit-pause'))$('#edit-pause').textContent='Pause';});$('#edit-pause')?.addEventListener('click',()=>{if(editVideo?.paused){editVideo.play();$('#edit-pause').textContent='Pause';}else{editVideo?.pause();$('#edit-pause').textContent='Play';}});$('#impact')?.addEventListener('input',e=>{editStage.style.setProperty('--impact',`${e.target.value}%`);const output=$('output[for="impact"]');if(output)output.value=e.target.value;});
}
function renderScene(i,impact=true){editIndex=(i+scenes.length)%scenes.length;const s=scenes[editIndex];if($('#edit-kicker'))$('#edit-kicker').textContent='';if($('#edit-title'))$('#edit-title').textContent=s.title;if($('#edit-subtitle'))$('#edit-subtitle').textContent=s.subtitle;$$('.timeline-step').forEach((step,n)=>{step.classList.toggle('active',n===editIndex);step.setAttribute('aria-current',n===editIndex?'step':'false');});if(impact&&motion&&editStage){editStage.classList.remove('impact');void editStage.offsetWidth;editStage.classList.add('impact');}}
const panelData=[['assets/phos-field.png','01 / BEFORE THE QUESTION','Wonder is a kind of courage.','Phos begins with a gaze that is always reaching past the next fact.'],['assets/phos-sun.png','02 / A LITTLE LIGHT','Joy arrives before it has a name.','The bright frame is brief, but it gives the early self a direction.'],['assets/phos-portrait.png','03 / THE FACE AS SYMBOL','Identity is watched into shape.','A face can become an emblem before the person inside it feels ready.'],['assets/phos-water.png','04 / THE BODY REMEMBERS','Loss changes the outline.','Water, reflection, and fracture make the body feel like an unfinished sentence.'],['assets/phos-crescent.png','05 / TOWARD THE MOON','Desire bends toward absence.','The moon turns distance into a physical pull: beautiful, cold, and impossible to hold.'],['assets/phos-hands.png','06 / HELD BY OTHERS','No fragment becomes alone.','The final image is ritual and relation: a self assembled through other hands.']];
const panelDialog=$('#panel-dialog');let panelIndex=0;
function showPanel(i){panelIndex=(i+panelData.length)%panelData.length;const [src,kicker,title,body]=panelData[panelIndex];if($('#dialog-panel-image')){$('#dialog-panel-image').src=src;$('#dialog-panel-image').alt=title;}if($('#dialog-panel-kicker'))$('#dialog-panel-kicker').textContent=kicker;if($('#dialog-panel-title'))$('#dialog-panel-title').textContent=title;if($('#dialog-panel-body'))$('#dialog-panel-body').textContent=body;}
$$('.manga-panel').forEach(panel=>panel.addEventListener('click',()=>{showPanel(Number(panel.dataset.panel));panelDialog?.showModal();}));$('#panel-prev')?.addEventListener('click',()=>showPanel(panelIndex-1));$('#panel-next')?.addEventListener('click',()=>showPanel(panelIndex+1));$('.panel-dialog .dialog-close')?.addEventListener('click',()=>panelDialog?.close());panelDialog?.addEventListener('click',e=>{if(e.target===panelDialog)panelDialog.close();});panelDialog?.addEventListener('keydown',e=>{if(e.key==='ArrowLeft')showPanel(panelIndex-1);if(e.key==='ArrowRight')showPanel(panelIndex+1);});
